### ISSUE TITLE
Netlify opzetten

### ISSUE THREAD

**Issue by Aratramba** [HogeschoolvanArnhemenNijmegen/HAN.nl#1]
@jennydebever kun jij hier een nieuwe Netlify-omgeving aan hangen? https://han.netlify.com? Zelfde instellingen (build-taak) als de pilot

**Comment by jennydebever** [comment]
het staat klaar, maar krijg 404, klopt dit?

**Comment by Aratramba** [comment]
klopt, er is nu geen homepage meer: https://han.netlify.com/deeltijd/
