### ISSUE TITLE
Schrijfrechten voor repository toekennen

### ISSUE THREAD

**Issue by hylmar** [HogeschoolvanArnhemenNijmegen/HAN.nl#28]
Kan iemand mij schrijfrechten toekennen voor de repository HAN.nl? Dan kan ik mijn bijdragen vanuit Eight pushen.

**Comment by Aratramba** [comment]
@IVARBureau @jennydebever ?

**Comment by jennydebever** [comment]
Hylmar heeft al schrijfrechten op de repository van HAN.nl, ik heb hem nu overall rechten gegeven.

Groet,
Jenny



Jenny de Bever | Webdeveloper | HAN ICT/SND Webbeheer | Ruitenberglaan 26 Arnhem | Kapittelweg 33  Nijmegen, kamer B0.05 |  T (06) 46 44 73 22 | jenny.debever@han.nl | www.han.nl



Werkdagen: maandag (Arnhem), dinsdag (Nijmegen), woensdag tot 14 uur (Nijmegen), donderdag (Arnhem), vrijdag tot 14 uur (Nijmegen)

Dringende vragen tijdens mijn afwezigheid: webbeheer@han.nl<mailto:webbeheer@han.nl>
________________________________
Van: Arjen <notifications@github.com>
Verzonden: donderdag 2 mei 2019 13:55
Aan: HogeschoolvanArnhemenNijmegen/HAN.nl
CC: Bever Jenny de; Mention
Onderwerp: Re: [HogeschoolvanArnhemenNijmegen/HAN.nl] Schrijfrechten voor repository toekennen (#28)


@IVARBureau<https://github.com/IVARBureau> @jennydebever<https://github.com/jennydebever> ?

**Comment by hylmar** [comment]
@jennydebever, toch kan ik nog niet schrijven naar de repository. Ook niet in de browser. Kun je nog een keer mijn rechten voor deze repository nagaan?

**Comment by hylmar** [comment]
Ik ben binnen, bedankt!
